syntax on
set number
set nowrap
set tabstop=2
set shiftwidth=2
set expandtab
set autoindent
set backspace=indent,eol,start
set showmatch
set backup
set backupdir=~/.vim/backup
set autoread
set encoding=utf-8
set ignorecase
set wrapscan
set ttyfast
set ambiwidth=double
set ruler
